# Generated by Django 4.2.5 on 2025-11-29 15:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.models.gerar_token, max_length=20, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('empresa', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('andamento', 'Em andamento'), ('analise', 'Em análise'), ('processo', 'Em processo'), ('finalizado', 'Finalizado')], default='andamento', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
